### PR TITLE
feat(drafts): Handle draft.process subject for generating PDF draft file

### PR DESCRIPTION
**Pull request by fajarhikmal214**
## Overview
- Handle `draft.process` subject for generating a PDF draft file
- Publish `draft.progress.update` subject for sending PDF draft file to core-service
- Refactoring some stuff like setup nats client
- I need to re-create (delete only, because it automatically created) the consumer to change the subject from `esign.process` to `*.process` to receive both `esign.process` and `draft.processs`

> Cannot directly update an existing consumer's `filter_subject or subject`. Once a consumer is created, its filter_subject and subject are fixed and cannot be modified

## Related Task:
- https://app.clickup.com/t/860qwqgak

## Evidence:
project: SIDEBAR
title: feat(drafts): Handle draft.process subject for generating PDF draft file
participants: @fajarhikmal214 @azophy @indraprasetya154 @muhamadabduh 
screenshot: https://github.com/jabardigitalservice/office-service-helper/assets/79292118/522e5db3-704e-4273-855d-4b0a8904baad

### CODE REVIEW

**Review by azophy — APPROVED** [review]
Just wish to clarify: From my understanding, the PDF generation for all drafts would be handled by helper service right? Core service only need to emit event everytime the draft content is changed, then the PDF file in Minio would be updated?

**Comment by azophy** [comment]
1 more question. regarding "draft" watermark generation, has it been handled? Would it be handled by FE or by using existing pdf service (the one in sidebar v1)?

**Review by indraprasetya154 — APPROVED** [review]

**Comment by indraprasetya154** [comment]
> 1 more question. regarding "draft" watermark generation, has it been handled? Would it be handled by FE or by using existing pdf service (the one in sidebar v1)?

if i see this PR, this PR only handled generate pdf file before user sign the document for preview purpose, right? CMIIW

**Comment by fajarhikmal214** [comment]
> Just wish to clarify: From my understanding, the PDF generation for all drafts would be handled by helper service right? Core service only need to emit event everytime the draft content is changed, then the PDF file in Minio would be updated?

That's right. But in the next PR, I will remove the previous file if there is exists

**Comment by fajarhikmal214** [comment]
> > 1 more question. regarding "draft" watermark generation, has it been handled? Would it be handled by FE or by using existing pdf service (the one in sidebar v1)?
> 
> if i see this PR, this PR only handled generate pdf file before user sign the document for preview purpose, right? CMIIW

It is, every single events that changes the document metadata will generate PDF with a draft watermark

**Review by muhamadabduh — APPROVED** [review]

**Pull request merged**
